# Generated by Django 2.2.9 on 2020-02-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
