# Generated by Django 2.2.9 on 2020-02-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20200210_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name_comp',
        ),
    ]
